title: "Nam Tran"
email: namkhaitran@csus.edu
description: # this means to ignore newlines until "baseurl:"
  Welcome to my page. Stuff will be comming soon...
baseurl: "/" 
url: "https://trankhainam97.github.io/" 
twitter_username: 
github_username:  trankhainam97

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg

theme: jekyll-theme-hacker